apiVersion: v1
kind: Service
metadata:
  name: event-consumer
spec:
  type: NodePort
  selector:
    app: event-consumer
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080  # <--- This makes it accessible from your browser on http://localhost:30001
